//   Copyright 2017 Wercker Holding BV
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package main

import (
	"text/template"
)

type Message struct {
	Name   string
	Fields []*Field
}

type Field struct {
	Comment string
	Name    string
	Type    string
}

var fileTemplate = template.Must(template.New("header").Parse(`
// @flow

// ------------------------------------
// Code generated by protoc-gen-flow
// source: {{.GetName}}
// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!
// ------------------------------------
`))

var messageTemplate = template.Must(template.New("message").Parse(`
declare type {{.Name}} = {|
	{{- range $field := .Fields}}
	{{$field.Name}}: {{$field.Type}};
	{{- end}}
|};
`))
