package main

import (
	"text/template"
)

type Message struct {
	Name   string
	Fields []*Field
}

type Field struct {
	Comment string
	Name    string
	Type    string
}

var fileTemplate = template.Must(template.New("header").Parse(`
// @flow

// ------------------------------------
// Code generated by protoc-gen-flow
// source: {{.GetName}}
// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!
// ------------------------------------
`))

var messageTemplate = template.Must(template.New("message").Parse(`
type {{.Name}} = {
	{{- range $field := .Fields}}
	{{$field.Name}}: {{$field.Type}};
	{{- end}}
};
`))
